### ISSUE TITLE
nitrous.io link returns 404

### ISSUE THREAD

**Issue by Nonemoticoner** [phonegap/phonegap-start#168]
https://github.com/phonegap/phonegap-start#nitrousio 

https://d3o0mnbgv6k92a.cloudfront.net/assets/hack-l-v1-3cc067e%28https://www.nitrous.io/hack_button?source=embed&runtime=nodejs&repo=phonegap%2Fphonegap-start&file_to_open=README.md 404 Not Found

Requires replacement.

**Comment by Nonemoticoner** [comment]
I belive this is the correct link. I created a PR with a fix.

**Comment by jessemonroy650** [comment]
@mwbrooks
This link is broken again. I don't know what the purpose of the link is.

I am about to make a pull request to fix up respository, cleanup all issues.
It will be a week before I make the request. Nov. 12, 2015 the earliest.
TIA
Jesse

**Comment by mwbrooks** [comment]
Hi @jessemonroy650,

We added the Nitrous.io link to support the project. However, since it continually breaks, I think we should consider removing it from the README.md.

Thoughts?

**Comment by arunthampi** [comment]
Hi everyone, I left nitrous last year and as far as I know this feature is no longer supported so you can feel free to remove it. Apologies for the trouble.

**Comment by mwbrooks** [comment]
@arunthampi Thanks for the info! I guess we can remove it

**Comment by Nonemoticoner** [comment]
So, remove entirely Nitrous from readme, right?

**Comment by mwbrooks** [comment]
See above commit, which removes Nitrous.io

@Nonemoticoner yep, look good to you?

**Comment by mwbrooks** [comment]
Sorry @Nonemoticoner, I didn't notice that you had a standing PR open for this as well, otherwise I'd have used that work.

**Comment by Nonemoticoner** [comment]
@mwbrooks It's okay. I'm not so much in PhoneGap anyway, now ;)
