### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by meth984** [phonegap/phonegap-start#172]
guys the version now is 4.1.2-0.22, but the start project is again 3.5.0. I have to change manually the version inside config.xml after I start new project?

**Comment by mwbrooks** [comment]
Thanks for the heads up @meth984!

I've updated the `config.xml` to default to the latest version of PGB: b27359124ec2e0556fa94ead67db89036e93ecb0 If you want to manually specify a different version, then you can uncomment the `phonegap-version` preference.
