### ISSUE TITLE
www/res/.pgbomit and icons

### ISSUE THREAD

**Issue by nofxx** [phonegap/phonegap-start#173]
When using remote or local:

Could not get any icons to show up until I removed the .pgbomit file from www/res.

PS.: local might be another bug, as I still cannot load any asset (works on remote).

**Comment by mwbrooks** [comment]
Hi @nofxx,

I'm about to test this out, but I thought I'd give you a quick update and ask a few questions. According to the [original post about .pgbomit](http://phonegap.com/blog/2014/04/11/phonegap-build-adds-some-new-features/), it only excludes the files from the app package but the files are available during the build process. The ideal use-case is for splashscreen and icons. So, I'm surprised that you're having issues with the icons not appearing.

Are you referring to the app icon shown on your devices home screen? Or are you trying to access the icon files from within in the app?

Cheers,
Michael

**Comment by mwbrooks** [comment]
Hi @nofxx,

After my own testing, it looks like the icons are splash screens are being used correctly. I downloaded the `phonegap-start` project and renamed `res/ -> _res/`. After uploading the PGB, the website icon was the PGB placeholder and the installed app homescreen icon was also the placeholder. I then renamed `_res/ -> res/` and re-uploaded the app. After the upload, the website icon became the `phonegap-start` icon and likewise the homescreen icon updated. In my test, I used a Android HTC One m8.

Looking forward to hearing your thoughts,
Michael

**Comment by nofxx** [comment]
Hello @mwbrooks , thanks for the quickly response, sorry my bad descripted issue (and english).

Local is ok `phonegap local build <plaftform>`  , my asset error is another issue.

Remote doesn't get icons `phone remote build <plaftform>` , now that I'm understanding things a lil better, guess it's the intended behaviour: only upload the res/ assets of the platform I'm compiling?
But not working, removing the pgbomit I see the whole folder is getting uploaded (1mb to 3mb) my APK.
And I get icons.

**Comment by jessemonroy650** [comment]
Does not seem to be an issue. Close.
