### ISSUE TITLE
CLI 3.6.3: Build Failed by adding platform="winphone" to XML

### ISSUE THREAD

**Issue by andreszs** [phonegap/phonegap-start#174]
Somehow, the PhoneGap team managed to completely screw up the build process from CLI when the following rule is added to the **config.xml** (required by Windows Dev Center)

`<gap:config-file platform="winphone" parent="/Deployment" mode="replace">
	<Languages>
		<Language code="es-ES"/>
		<Language code="es-MX"/>
	</Languages>
	<DefaultLanguage xmlns="" code="es-MX" />
</gap:config-file>`

**Was it so hard to just *ignore* unknown XML parameters?** Does the build process REALLY HAS TO FAIL because the CLI does not understand a few lines of XML code from config.xml? Who implemented this *great* feature?

A decent parser would simply report *"hey, I ignored line X from config.xml because I don't understand it"* and go on with the build process.

Please, in the future make sure only actual developers take care of XML parsing routines, that is, a person that actually knows what he/she's doing.

**Comment by jessemonroy650** [comment]
@andreszs 
This is not an issue for this app (example). This is an issue with the parser. I am closing it for that reason.

While I understand, this is in the end an issue with XML. And to be clear, the exact reason you are writing this complaint is the exact reason may people do not to use XML. There are better formats.
TIA
Jesse

**Comment by jessemonroy650** [comment]
Not an issue. Close.
