### ISSUE TITLE
Google Play says app requires 17 permissions

### ISSUE THREAD

**Issue by Monsignor** [phonegap/phonegap-start#178]
I set <preference name="permissions" value="none"/> as this example suggests, but when I upload the APK to Google Play, it says that it will require 17 permissions and 5 features in order to be installed.

I'm not using any special libraries that may require these permissions, just Bootstrap and jQuery. The strange thing is, even when I remove all content from my index.html (the only HTML file in the app) the same thing happens.

Any ideas how I can remedy this? The app will onlye require network access for now.

I am not using Cordova and I don't have a Manifest.xml, just config.xml.

**Comment by vishymuku** [comment]
In my config.xml, i have only the following preferences. Nothing else. The app asks only for network permission. BTW i use phonegapbuild service. hope this helps.

<preference name="permissions"                value="none"/>
    <preference name="phonegap-version"           value="3.7.0" />          
    <preference name="orientation"                value="landscape" />        
    <preference name="target-device"              value="universal" />      
    <preference name="fullscreen"                 value="true" />           
    <preference name="webviewbounce"              value="false" /> 
    <preference name="stay-in-webview"            value="true" />   
    <preference name="detect-data-types"          value="true" />           
    <preference name="exit-on-suspend"            value="true" />          
    <preference name="show-splash-screen-spinner" value="true" />           
    <preference name="auto-hide-splash-screen"    value="true" />          
    <preference name="disable-cursor"             value="false" />          
    <preference name="android-minSdkVersion"      value="7" />              
    <preference name="android-installLocation"    value="auto" />    
	
    <icon src="icon.png" />
    <gap:splash src="splash.png" />
	
    <access origin="*"/>

**Comment by jessemonroy650** [comment]
Not an issue. Close.
