### ISSUE TITLE
Update config.xml android-minSdkVersion

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-start#182]

**Comment by jessemonroy650** [comment]
@Simon,
I appreciate there should be a working config.xml. However, we need a master config.xml example to point people to. The documenation is confusing, conflicting and missing. Especially with this point.

**Comment by jessemonroy650** [comment]
@macdonst
I'm going to make a pull request to update this issue. This field will go in the comments, like the phonegap-version.
TIA
Jesse

**Comment by macdonst** [comment]
@jessemonroy650 I'm cool with it being commented out but if you create a new project and this template is pulled in their will be compile time problems.

**Comment by jessemonroy650** [comment]
You mean I'll get a headache from the stupidity. I already have that. Any changes I make will have enough comments so that end-user can back out those changes. Yes, that means I should comment out stuff and not delete it. Thanks for the reminder. :-)
