### ISSUE TITLE
Why cordova-plugin-whitelist not using gap: namespace?

### ISSUE THREAD

**Issue by slorber** [phonegap/phonegap-start#183]
Hi

the `cordova-plugin-whitelist` is the only one not using the gap: namespace.
What is the reason? What is the difference between gap:plugin and plugin? Could not find a clear answer in documentation so asking here...

See also http://stackoverflow.com/questions/31341406/cordova-phonegap-plugin-add-vs-config-xml

**Comment by jessemonroy650** [comment]
@slorber 
I have added comments to that SO thread. This will also help.

<a href=https://github.com/jessemonroy650/top-phonegap-mistakes/blob/master/the-whitelist-system.md>HOW TO apply the Cordova/Phonegap the whitelist system</a>

**Comment by jessemonroy650** [comment]
No issue. Close.
