### ISSUE TITLE
Alert on first start

### ISSUE THREAD

**Issue by kayyyy** [phonegap/phonegap-start#184]
Hi,

currently i am testing phonegap. I installed the example and started the app with the mac phonegap app. If i visit the browser i get everytime several alerts.

![image](https://cloud.githubusercontent.com/assets/8193345/9156231/d80c6766-3ed2-11e5-87e5-595fbd3b688a.png)

Did i something wrong or why am i getting these alerts?

**Comment by mwbrooks** [comment]
Hi @kayyyy,

The app is intended to be compiled and run on iOS, Android, or WP. You are seeing that alert because you are trying to run the app in a regular desktop browser.

**Comment by kayyyy** [comment]
@mwbrooks Ah okay - thanks :+1:

**Comment by mwbrooks** [comment]
Cool. Although... we should see desktop browser support for development / debugging soon! That day can't come soon enough!

**Comment by kayyyy** [comment]
@mwbrooks I just found out that Phonegap Desktop automatically synchronized the iPhone in real time with your current Development, awesome. :+1: 

But because the browser Support: I currently working with the ionicframework and there is no problem if you load the App in your Browser :)

**Comment by barry-bhinderjit** [comment]
can you solve this michael, i am working on it from weeks but could not
find way out

http://stackoverflow.com/questions/31924566/want-to-share-html-to-pdf-converted-file-using-kendo-phonegap
