### ISSUE TITLE
Erro when compiled pure start version in Phonegap Build

### ISSUE THREAD

**Issue by andreluizmorita** [phonegap/phonegap-start#185]
Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: FileTransfer.java - You can fix this here

**Comment by barry-bhinderjit** [comment]
I use phone gap version 3.7 to resolve that error for now.

**Comment by andreluizmorita** [comment]
Thank. Its working

I put <preference name="phonegap-version" value="3.7.0" /> in my config.xml and working.

Thanks
