### ISSUE TITLE
What config.xml should be to remove the default splash screen?

### ISSUE THREAD

**Issue by liuzhen2008** [phonegap/phonegap-start#186]
I want to not show any splash screen at all for my app.

Just .. w/e the OS decides to put on.

How do I achieve that in my config.xml on phonegap build?

**Comment by barry-bhinderjit** [comment]
just go build.phonegap. com and click on docs then splashscreen, you can find all info over there.

**Comment by jessemonroy650** [comment]
Not an issue. Close.
