### ISSUE TITLE
Out of date phonegap-start

### ISSUE THREAD

**Issue by AlexPashley** [phonegap/phonegap-start#188]
Hi Simon,

fantastic example project!! I was wondering if you had time to maybe update the config.xml so we can see a working example with the new PGB version 5.2.0. I find a lot of the PhoneGap documentation quite misleading as a lot of the examples are for the cli not for PGB and it doesnt seem to get updated that much :(

Again thanks for taking your time to make this as this has been invaluable for me in the past.

Regards,

Alex

**Comment by jessemonroy650** [comment]
@AlexPashley,
I'm making changes to *phonegap-start*. If you have any suggestions for this APP (only). This is the time.

TIA
Jesse

**Comment by AlexPashley** [comment]
Would be great to see all of the phones new splash screens & icons 

Also potentially including FastClick if you deem this necessary?

**Comment by jessemonroy650** [comment]
@AlexPashley splashscreen are optional and there is debate whether they should be used. Icons are included with the default build; you just need to replace them. 

Recently, webkit decide to remove the 300ms delay. This make fastclick un-nessecary. However, it may be a year or more before we see the change. The replacement of the webview library is not a trivial task.
