### ISSUE TITLE
i insatll phonegap and type my server url also, it says Download Error ( not connecting to windows phone)?

### ISSUE THREAD

**Issue by trinadhvidavaluru** [phonegap/phonegap-start#194]
i insatll phonegap and type my server url also, it says Download Error ( not connecting to windows phone)?

**Comment by mwbrooks** [comment]
Hi @trinadhvidavaluru,

Can you please re-submit the issue to [phonegap/phonegap-app-developer/issues](https://github.com/phonegap/phonegap-app-developer/issues). We will need more information, such as:
- Are using the PhoneGap CLI or PhoneGap Desktop?
- Are you using Windows or OS X?
- Are your computer and phone on the same network (they must be)?
- Does your network support peer-to-peer connections (no software or hardware firewall)?

Thanks!
Michael

**Comment by trinadhvidavaluru** [comment]
Hi mwbrooks,
I'm using 'PhoneGap Desktop' on windows os, it is connected to windows phone but i'm putting image in my site then it gives download error (my computer and phone on the same network), it works in browser why?

Q) how to connect to oracle database using phonegap?, where we write services in phonegap desktop on windows os?

**Comment by mwbrooks** [comment]
Hi @trinadhvidavaluru,

Please submit the issue to https://github.com/phonegap/phonegap-app-developer/issues for someone to help you out.

Re: Oracle database. Similar to any thick-client web app, you must interact with the Oracle database using a Web API (e.g. RESTful).
