### ISSUE TITLE
I'm using 'PhoneGap Desktop' on windows os, it is connected to windows phone but i'm putting image in my site then it gives download error.

### ISSUE THREAD

**Issue by trinadhvidavaluru** [phonegap/phonegap-start#196]
I'm using 'PhoneGap Desktop' on windows os, it is connected to windows phone but i'm putting image in my site then it gives download error (my computer and phone on the same network), it works in browser why?

Q) how to connect to oracle database using phonegap?, where we write services in phonegap desktop on windows os?

**Comment by mwbrooks** [comment]
Duplicate to #194

Please submit this issue to http://github.com/phonegap/phonegap-app-developer/issues
