### ISSUE TITLE
Splashscreen dont Work

### ISSUE THREAD

**Issue by kasik96** [phonegap/phonegap-start#199]
Hi,
When you Clone this project and build in in PhoneGap Build, Splashscreen will dont work.
And thats not only problem. This project is super outdated but is used for Starting project in PhoneGap Desktop App. I think it really needs update to work.

**Comment by englishextra** [comment]
https://github.com/phonegap/phonegap-start/issues/198

**Comment by appglobaltech** [comment]
Hi
I found why splash screen is not coming...because in the name tag there is space between Hello and World....remove that space you can see the splash screen....but this is the issue...want solution of this...

**Comment by macdonst** [comment]
Hi, we don't really track the issues on this repo and we ask that folks having problems with PhoneGap please use our forum:

https://forums.adobe.com/community/phonegap
