### ISSUE TITLE
in PushwooshAndroid.js file, GOOGLE_PROJECT_ID should be GOOGLE_PROJECT_NUMBER

### ISSUE THREAD

**Issue by brobinson-ert** [phonegap/phonegap-start#204]
In PushwooshAndroid.js file, the comment about the google project id and the key name, "projectid", are very misleading.  Since they refer to the project number in the google developer console and there is a project id in the developer console, it would be helpful if the comment and the key name referred to project number.  Thanks.

**Comment by bogz22** [comment]
Thanks

**Comment by macdonst** [comment]
Hi, we don't really track the issues on this repo and we ask that folks having problems with PhoneGap please use our forum:

https://forums.adobe.com/community/phonegap
