### ISSUE TITLE
How will i disable debugging in a phonegap APK before published in Google Play?

### ISSUE THREAD

**Issue by websumon** [phonegap/phonegap-start#210]
I have built apk by PhoneGap but when i upload it in google play then google play show me this massage

Upload failed: 1. You uploaded a debuggable APK. For security reasons you need to disable debugging before it can be published in Google Play. Learn more about debuggable APKs.

2.You uploaded an APK that was signed in debug mode. You need to sign your APK in release mode. Learn more about signing.

how can i solve it ?

**Comment by englishextra** [comment]
If you generate your apk at https://build.phonegap.com/apps/

you should click on appname (blue color link)
choose settings
and uncheck Enable debugging 

At least worth trying if you haven't done that step yet.

**Comment by shazron** [comment]
This issue is irrelevant to this repo, and don't cross post: https://github.com/phonegap/phonegap-template-hello-world/issues/20. Try using the `--release` flag when generating the app using the CLI.
