### ISSUE TITLE
Infinite Initializing application on Mobile

### ISSUE THREAD

**Issue by Onchman** [phonegap/phonegap-start#211]
Hi everyone,

I started using Phonegap some days ago. Trying to use https://build.phonegap.com to build an apk for Android.

It worked, i downloaded this apk thanks to the QR Code, installed it on my Huawei Honor 8, with Android 6.0 version. 

When I launch the application, "Hydra" ask me to update my application, it retrieve new contents. 

And then, i have a "Initalizing. Please wait" page, but, nothing happen. I waited for 30 min to see if something changed, but, the loading icon does not stop to turn.

I attach with this my config.xml, if you need something else, don't hesitate to ask me :)

Best regards, D.Braz.
[confing.txt](https://github.com/phonegap/phonegap-start/files/764039/confing.txt)

**Comment by englishextra** [comment]
https://github.com/phonegap/phonegap-start/issues/210
