### ISSUE TITLE
Not Working in IOS

### ISSUE THREAD

**Issue by himanshutecstub** [phonegap/phonegap-start#213]
I use same code for create ios app on https://build.phonegap.com but below code not working in ios 9.3.5 version.
i also add phonegap version in `config.xml` file.
`<preference name="phonegap-version" value="cli-6.5.0" />`
In that file app.initialize() not working event if custom script i tried which also not working.

**Comment by macdonst** [comment]
Hi, we don't really track the issues on this repo and we ask that folks having problems with PhoneGap please use our forum:

https://forums.adobe.com/community/phonegap
