### ISSUE TITLE
package org.apache.cordova.file does not exist

### ISSUE THREAD

**Issue by heanfig** [phonegap/phonegap-start#221]
when i compile with phonegap build show this error

`/project/src/org/apache/cordova/filetransfer/FileTransfer.java:49: error: package org.apache.cordova.file does not exist`

```
/project/src/org/apache/cordova/filetransfer/FileTransfer.java:851: error: cannot find symbol
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");
```

![sin titulo](https://user-images.githubusercontent.com/4906962/32814373-c01b0a18-c97c-11e7-943f-1dd35f6c2cb8.png)

**Comment by gwokudasam** [comment]
has anyone found a solution for this yet?

**Comment by jensbroecher** [comment]
Same problem

**Comment by englishextra** [comment]
```xml
<plugin name="cordova-plugin-file" spec="4.3.3"/>
<plugin name="cordova-plugin-file-transfer" spec="1.6.3"/>
```
should builds for both iOS and Android. (CLI 7.0.1) or

```xml
<gap:plugin name="cordova-plugin-file"  source="npm" spec="~4.3.3"/>
<gap:plugin name="cordova-plugin-file-transfer"  source="npm"  spec="~1.6.3"/>
```

**Comment by macdonst** [comment]
Hi, we don't really track the issues on this repo and we ask that folks having problems with PhoneGap please use our forum:

https://forums.adobe.com/community/phonegap
