### ISSUE TITLE
Splash Screen for iPhone 5 is not updated

### ISSUE THREAD

**Issue by shunner** [phonegap/phonegap-start#91]
Note that /www/res/screen/ios/screen-iphone-portrait-568h-2x.png still shows the icon from Apache Cordova.

So please make appropriate changes to keep consistency of phonegap-start.

Thanks~

**Comment by nofxx** [comment]
It's fixed in 3.x. If someone would like to close it.

**Comment by mwbrooks** [comment]
Thanks for the heads up @nofxx!
